### ISSUE TITLE
Updates to mplot_label

### ISSUE THREAD

**Issue by JackBuckley** [e61-Institute/theme61#49]
- Allow right/left align of text ✅ 
 - ~~Auto wrap labels, similar to labs_e61~~
 - ~~Use factor levels for colours, i.e. add an option to just supply the variable name~~
 - Add ability to have boxes around labels ✅

Note: Edited by @aaronw22

**Comment by aaronw22** [comment]
Future notes for when someone gets around to implementing these ideas:

* Can be done by specifying `hjust = 0` as an argument in the underlying `annotate()` function.
* Not sure about the utility of this. Text labels aren't often that long, and squeezing them into little gaps in between lines probably requires a different line break point for each label rather than a consistent one.
* This will be hard to do and might require refactoring the whole thing into a custom `geom_`, which I don't know how to do, or how to do it without breaking the existing flexibility. Aside: you can get the label names to be correctly ordered if your colour/fill column is an ordered factor and you specify the label names as `levels(data$column)`.
* Might be doable by making it possible to change `geom = "text"` to `geom = "label"`.

**Comment by aaronw22** [comment]
FYI @JackBuckley I won't be attempting to implement points 2 and 3 for reasons above.
